name: Pasteboard
options:
  bundleIdPrefix: com.sinaanahd
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    CODE_SIGN_STYLE: Automatic
targets:
  Pasteboard:
    type: application
    platform: macOS
    sources: [Pasteboard]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sinaanahd.Pasteboard
        PRODUCT_NAME: Pasteboard
        MARKETING_VERSION: 1.1.0
        CURRENT_PROJECT_VERSION: 2
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleShortVersionString: "$(MARKETING_VERSION)"
        INFOPLIST_KEY_CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Sina Nahd"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: NO
    scheme:
      testTargets: [PasteboardTests]
  PasteboardTests:
    type: bundle.unit-test
    platform: macOS
    sources: [PasteboardTests]
    dependencies:
      - target: Pasteboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sinaanahd.PasteboardTests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
