import AppKit
import XCTest
@testable import Pasteboard

final class PasteboardPrivacyFilterTests: XCTestCase {
    func testOrdinaryClipboardTypesAreCaptured() {
        XCTAssertTrue(PasteboardPrivacyFilter.shouldCapture(types: [.string, .png]))
    }

    func testSensitiveAndTransientClipboardTypesAreExcluded() {
        XCTAssertFalse(PasteboardPrivacyFilter.shouldCapture(types: [.string, PasteboardPrivacyFilter.concealedType]))
        XCTAssertFalse(PasteboardPrivacyFilter.shouldCapture(types: [PasteboardPrivacyFilter.transientType]))
        XCTAssertFalse(PasteboardPrivacyFilter.shouldCapture(types: [PasteboardPrivacyFilter.autoGeneratedType]))
    }
}
