import AppKit

enum PasteboardPrivacyFilter {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        concealedType,
        transientType,
        autoGeneratedType
    ]

    static func shouldCapture(types: [NSPasteboard.PasteboardType]) -> Bool {
        excludedTypes.isDisjoint(with: types)
    }
}
